#pragma once
#define NOMINMAX
#include <SimpleMath.h>
#include <memory>
#include <vector>
#include <deque>
#include <unordered_set>
#include <wrl/client.h>
#include <iostream>
#include <algorithm>
#include <cmath>
#include <d3d11.h>
#include <DirectXMath.h>
#include <io.h>
#include <string>
#include <functional>
#include <Windows.h>
#include	<assimp/Importer.hpp>
#include	<assimp/scene.h>
#include	<assimp/postprocess.h>
#include	<assimp/cimport.h>
#include	<d3dcompiler.h>
#include	<locale.h>
#include <unordered_map>
#include	<filesystem>
#include <map>
#include <random>
#include <DirectXColors.h>
#include <PrimitiveBatch.h>
#include <VertexTypes.h>
#include <CommonStates.h>
#include <Effects.h>
#include <any>
#include <atomic>
#include <queue>
#include <future>
#include <optional>
#include <typeindex>
#include <chrono>
#include    <cstdint>
#include <fstream>
#include <utility> 
#include <Xinput.h> 
#include <stdio.h>
#include <assert.h>
#include	<cassert>
#include <cfloat>
#include <numeric>
#include <type_traits>
#include <thread>
#include <sstream>
#include <tchar.h>

#undef min
#undef max


